//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druzyna
    {
        public int NrZawodnika { get; set; }
        public Nullable<int> NrKoszulki { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public string Pozycja { get; set; }
        public string Kraj { get; set; }
    }
}
